### ISSUE TITLE
Juice Shop Challenge Pins

### ISSUE THREAD

**Issue by bkimminich** [wurstbrot/security-pins#10]
During classes or hacking events it would be nice to hand out additional pins not focused on vulnerability (sub-)categories (like XSS, Angular XSS, NoSQLi etc.) but also for completing challenges of the Juice Shop. I see two possible paths which would also work nicely in combination:

## Difficulty Level Pins
This would require six new badges what should show the corresponding number of stars and maybe also the difficulty level name. They would be handed out when someone has completed all challenges of the given difficulty.
1. :star: = Trivial
2. :star::star: = Easy
3. :star::star::star: = Medium
4. :star::star::star::star: = Hard
5. :star::star::star::star::star: = Dreadful
6. :star::star::star::star::star::star: = Diabolic

## Score Board Completion Pins
This could be done by having %-based Score Board completion badges which would be given out when someone passes the corresponding threshold.
1. \>25% challenges solved = Bronze
2. \>50% challenges solved = Silver
3. \>75% challenges solved = Gold
4. 100% challenges solved = Diamond

# Some visualization ideas
* The Juice Shop logo or the CTF logo variation should at least in part be visible on the badge (could also be background, like you're currently doing with the OWASP wasp on other pins)
* If using the CTF logo in the foreground
  * the flag itself could contain the number of stars or the %-value
  * the color of the flag could indicate the level/quality of the badge
* The relevant content on the badge should not be too small, so maybe just showing a zoomed-in but still recognizable piece the Juice Shop (or CTF) logo would do nicely

# Links/Resources
* https://juice-shop.herokuapp.com/#/score-board
* https://bkimminich.gitbooks.io/pwning-owasp-juice-shop/content/part2/
* https://github.com/OWASP/owasp-swag/tree/master/projects/juice-shop

**Comment by wurstbrot** [comment]
@ktreptow is working on this one

**Comment by wurstbrot** [comment]
@ktreptow are you/will you work on this one? Otherwise I will hire a designer shortly to have the pins soon.

**Comment by ktreptow** [comment]
Currently working on this! Should be done by the end of the week. Thank you both for your patience. :)

**Comment by ktreptow** [comment]
Hello @bkimminich , hello @wurstbrot 
the following are a few possible versions for the **Difficulty Level Pins**. 
![overview svg](https://user-images.githubusercontent.com/37484788/58492694-b802f580-8171-11e9-9476-7fae8210c1b8.png)
(v7 was made after @wurstbrot gave feedback last week.) 

These are a suggestion for the **Completion Pins**

![25-percent svg](https://user-images.githubusercontent.com/37484788/58492873-15974200-8172-11e9-91f8-cecdfa6348b4.png)

Please let me know, which version you like most and if you have any remarks or suggestions.

**Comment by bkimminich** [comment]
🥇 v6
🥈 v3
🥉 v1 (although the shadow of the wasp doesn't work so well for me)

**Comment by bkimminich** [comment]
The idea with the logo "filling" up for the %-pins is really nice!
* Variation idea 1: Zoom in the logo onto the flag and write "25%" etc. _into the flag_ 
* Variation idea 2: Instead of filling the logo let the size of the juice puddle indicate the completion

**Comment by bkimminich** [comment]
Also, it seems you used some weird merge of the original logo (with the hole leaking at the bottom left) and the one with the flag piercing through...?

![image](https://user-images.githubusercontent.com/3531020/58494628-d4a12c80-8175-11e9-82ef-5100b5ac3c92.png)

versus

![image](https://user-images.githubusercontent.com/3531020/58494681-f1d5fb00-8175-11e9-9997-c588ff2ef78c.png)

**Comment by ktreptow** [comment]
Hey @bkimminich, hey @wurstbrot 
I altered the existing pins a bit and added stars to them. An alternative can be seen with the "Injection"-Pins down below, where I used the stars from the pins above, although I personally like the other version more. 

![summary svg](https://user-images.githubusercontent.com/37484788/58714860-f5f85780-83c5-11e9-80a8-442960df0692.png)


We didn't have any for "Broken Access Control" yet, so I made one. Please let me know if you want anything changed. 

The poster would look like this with the new pins. 
![poster svg](https://user-images.githubusercontent.com/37484788/58714879-ff81bf80-83c5-11e9-8652-3b80583afe27.png)

Have a nice weekend!

**Comment by wurstbrot** [comment]
@ktreptow thank you!
Do you mind creating a PR?

**Comment by wurstbrot** [comment]
Broken Auth and Injection are some kind pushed to the left (not middle).

**Comment by wurstbrot** [comment]
@ktreptow By printing the poster in A2, which size does the pins (e.g. https://github.com/wurstbrot/security-pins/blob/master/juice-shop-challenge-pins/Pins/PNG/no-background/broken_authentification4.png) need to have?

**Comment by wurstbrot** [comment]
@ktreptow By printing the poster in A3, which size does the pins (e.g. https://github.com/wurstbrot/security-pins/blob/master/juice-shop-challenge-pins/Pins/PNG/no-background/broken_authentification4.png) need to have?

**Comment by bkimminich** [comment]
I just printed one in s/w on normal paper, and the stickers would be exactly the size of a 2€ coin.
