### ISSUE TITLE
Sticker Poster

### ISSUE THREAD

**Issue by bkimminich** [wurstbrot/security-pins#11]
As a way to show off the collected stickers an approach similar to the classic "Panini Sammelalbum" would be nice - just as a poster to hang on your office wall!

## Design Ideas
* should feature some nice background artwork
* topics could be grouped as paths or clusters, e.g. all XSS-related or Injection-related stickers belong close to each other
* should have some blank slots for future stickers for which no known groups/paths exist already

Personally I think this would be nice alternative to the hat with pins, as the Security Champions would also _see the empty spaces_ on their poster and might be more motivated to fill those with stickers.

**Comment by ktreptow** [comment]
Hey @bkimminich !
Below is a first draft for the Sticker Poster. 
The circles inside the clouds could contain the corresponding pin in greyscale or the challenges' name or theme. 

Additionally, I could write the topics underneath the clouds. 
![poster svg](https://user-images.githubusercontent.com/37484788/58492291-e16f5180-8170-11e9-8b88-c43c3441b380.png)

**Comment by wurstbrot** [comment]
@ktreptow 
For the start, we would love to have a poster with the following categories/stars:
"XSS": 1, 3, 4
"Injection": 2, 3, 4
"Broken Authentication": 2,3, 4
"Broken Access Control": 2,3, 4 (old broken authorization)

We do not want the specific "SQL Design" from existing pins, we will take the one from https://github.com/wurstbrot/security-pins/issues/10 . But a combination of stars with existing is possible and would give a nice look and feel.

As discoused, it would be nice to have the pins/stickers faded out in the poster.

In case you need more randomness for random sizes of cloud, Injection can have two times 4 stars and Broken Authentication 5 stars in addition.

In case "Broken Authorization" is too long, you might remove "Broken" from Auth*

**Comment by bkimminich** [comment]
I'd go with "Broken Access Control" actually to make it easier to distinguish from "Broken Authentication". People always mix those up... 😁  ... Just a though! Otherwise nice idea to build on the wallpaper cloud-design! 👍

**Comment by wurstbrot** [comment]
@bkimminich In case "Broken Access Control" is too long, what is your suggestion?

**Comment by bkimminich** [comment]
"⚡️ Access Ctrl" maybe? 😀

**Comment by bkimminich** [comment]
Or just "Access Control" but letting the letters appear broken/falling apart. Could be the same for "Authentication" maybe.
