### ISSUE TITLE
Security Champion Pin

### ISSUE THREAD

**Issue by wurstbrot** [wurstbrot/security-pins#15]
We do have an "OWASP Security Pins" pin, but no "Security Champion" pin.
An other company is thinking of giving out pins, but do not want to give out pins/sticker each time, just once in a while. The first pin should be a "Security Champion" pin.

@ktreptow Ideas?

**Comment by ktreptow** [comment]
If there some form of documentation of attendance, there could be pins given out when a certain number of attendances is achieved. Pins could be given out every 5 / 10 / 15 ... participations.

Alternatively or even additionally, there could be a pin solely for the teams champion, sort of like a badge. This pin would be given out just once at the start of the persons "champion role".

**Comment by UxityHub** [comment]
![Mockup 72](https://user-images.githubusercontent.com/59837345/72271109-4c13c580-364c-11ea-9328-de650e30c8e7.jpg)

Kindly check  this and let me if can mistake
