### ISSUE TITLE
is there a License?

### ISSUE THREAD

**Issue by northdpole** [wurstbrot/security-pins#22]
Hey team, love this project and great work for maintaining it!
I'd love to use this but I'd like to know what the license is.

Moreover, is there a way to make it more apparent that specific pins are under specific licenses? e.g. putting them under their own dir structure?

In it's current format it is too easy to violate licenses by missing the README

**Comment by wurstbrot** [comment]
Please take a look at https://github.com/wurstbrot/security-pins/blob/master/LICENCE

**Comment by wurstbrot** [comment]
@northdpole Pins with (potential) license issues have been moved to https://github.com/wurstbrot/security-pins/tree/add-license-1
